services:
  - type: static
    name: manwon-generator
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /
        destination: /index.html
    headers:
      - path: /*
        name: X-Robots-Tag
        value: index