services:
  - type: web
    name: manwon-generator
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FORCE_REBUILD
        value: "2025-08-08-DOCKER-DEPLOY"