services:
  - type: web
    name: manwon-generator
    runtime: python3
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    autoDeploy: true